<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net4.6.2</TargetFramework>
        <IsPackable>false</IsPackable>
        <RootNamespace>SuperScroll.Tests</RootNamespace>
        <AssemblyName>SuperScroll.Tests</AssemblyName>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\SuperScroll.csproj" />
    </ItemGroup>
</Project>
